/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExtractRouteImport } from './routes/api/extract'
import { Route as DownloadTokenRouteImport } from './routes/download/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadTokenRoute = DownloadTokenRouteImport.update({
  id: '/download/$token',
  path: '/download/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/extract': typeof ApiExtractRoute
  '/download/$token': typeof DownloadTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/extract': typeof ApiExtractRoute
  '/download/$token': typeof DownloadTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/extract': typeof ApiExtractRoute
  '/download/$token': typeof DownloadTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/extract' | '/download/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/extract' | '/download/$token'
  id: '__root__' | '/' | '/api/extract' | '/download/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiExtractRoute: typeof ApiExtractRoute
  DownloadTokenRoute: typeof DownloadTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$token': {
      id: '/download/$token'
      path: '/download/$token'
      fullPath: '/download/$token'
      preLoaderRoute: typeof DownloadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiExtractRoute: ApiExtractRoute,
  DownloadTokenRoute: DownloadTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
