// Generated by apps/web/scripts/og/generate.ts. Do not edit by hand: run `bun run generate`.
export const shareAssets = {
  "inputsHash": "f2fc3f67f32d9b1edc7c4fa4df505aea483ea59a76d49e11e7e2ec0b1c45f6e7",
  "ogZh": {
    "path": "/share/og-zh.png",
    "version": "6cb5f1e7",
    "width": 1200,
    "height": 630
  },
  "ogEn": {
    "path": "/share/og-en.png",
    "version": "15fd1527",
    "width": 1200,
    "height": 630
  },
  "square": {
    "path": "/share/square.png",
    "version": "b91702d1",
    "width": 600,
    "height": 600
  },
  "favicon32": {
    "path": "/favicon-32.png",
    "version": "559beb67",
    "width": 32,
    "height": 32
  },
  "appleTouchIcon": {
    "path": "/apple-touch-icon.png",
    "version": "14c0259c",
    "width": 180,
    "height": 180
  }
} as const
