/**
 * Builds the share images and icon PNGs from the page copy, public/logo.svg and the committed fonts, and
 * records what it made in src/share-assets.gen.ts. `build` does all the work in memory and fails before any
 * file is written; `write` then puts the result on disk.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { Schema } from "effect"
import { pageCopy, type Locale, type PageCopy } from "../../src/i18n.ts"
import { figtreeDir, loadFonts, missingGlyphs, readFontLock, sha256, verifyFontFiles, type FontSet } from "./font-store.ts"
import { encodeIndexedPng, parsePng, quantize } from "./png.ts"
import { drawSvg, rasterizePng, rasterizeRgba } from "./render.ts"
import { cardTexts, locales } from "./share-texts.ts"
import { BRAND_COLORS, INK, ogCard, squareCard, svgDataUri } from "./templates.ts"
import type { ReactElement } from "react"

const here = (path: string): string => fileURLToPath(new URL(path, import.meta.url))

export interface Paths {
  /** apps/web/public/logo.svg, the one source of the mark. */
  readonly logo: string
  readonly fontsDir: string
  /** apps/web/public. The share images and the icon PNGs are written under it. */
  readonly publicDir: string
  /** apps/web/src/share-assets.gen.ts */
  readonly assetsModule: string
}

export function defaultPaths(): Paths {
  return {
    logo: here("../../public/logo.svg"),
    fontsDir: here("./fonts/"),
    publicDir: here("../../public/"),
    assetsModule: here("../../src/share-assets.gen.ts"),
  }
}

/** Output paths, relative to the public directory. */
const OUTPUT = {
  ogZh: "share/og-zh.png",
  ogEn: "share/og-en.png",
  square: "share/square.png",
  favicon32: "favicon-32.png",
  appleTouchIcon: "apple-touch-icon.png",
} as const

const MAX_COLORS = 64

interface Limits {
  readonly wide: number
  readonly square: number
}

const DEFAULT_LIMITS: Limits = { wide: 25 * 1024, square: 8 * 1024 }

// ---------------------------------------------------------------- the recorded assets

const ImageInfo = Schema.Struct({
  path: Schema.String.check(Schema.isPattern(/^\/[\w./-]+\.png$/)),
  version: Schema.String.check(Schema.isPattern(/^[0-9a-f]{8}$/)),
  width: Schema.Number.check(Schema.isInt()),
  height: Schema.Number.check(Schema.isInt()),
})

const AssetsSchema = Schema.Struct({
  inputsHash: Schema.String.check(Schema.isPattern(/^[0-9a-f]{64}$/)),
  ogZh: ImageInfo,
  ogEn: ImageInfo,
  square: ImageInfo,
  favicon32: ImageInfo,
  appleTouchIcon: ImageInfo,
})

export type ShareAssets = typeof AssetsSchema.Type

const MODULE_HEADER = "// Generated by apps/web/scripts/og/generate.ts. Do not edit by hand: run `bun run generate`.\n"

function moduleSource(assets: ShareAssets): string {
  return `${MODULE_HEADER}export const shareAssets = ${JSON.stringify(assets, null, 2)} as const\n`
}

const messageOf = (error: unknown): string => (error instanceof Error ? error.message : String(error))

/** Reads share-assets.gen.ts back. The file is ours, but it is still data from disk, so it is decoded, not cast. */
function parseModule(source: string): ShareAssets {
  if (!source.startsWith(MODULE_HEADER)) throw new Error("it does not start with the generated-file header")
  const match = /^export const shareAssets = ([\s\S]*) as const\n$/.exec(source.slice(MODULE_HEADER.length))
  if (match === null) throw new Error("it is not shaped like the file the generator writes")
  let value: unknown
  try {
    value = JSON.parse(match[1] ?? "")
  } catch (error) {
    throw new Error(`its object is not valid JSON: ${messageOf(error)}`, { cause: error })
  }
  return Schema.decodeUnknownSync(AssetsSchema)(value)
}

const PackageSchema = Schema.Struct({
  devDependencies: Schema.Struct({ satori: Schema.String, "@resvg/resvg-wasm": Schema.String }),
})

// ---------------------------------------------------------------- inputs

/** Everything that decides what the images look like. A change to any of it makes `generate:check` fail until the images are regenerated. */
function computeInputsHash(paths: Paths, copyFor: (locale: Locale) => PageCopy): string {
  const sources = ["generate.ts", "png.ts", "render.ts", "templates.ts", "share-texts.ts", "font-store.ts"].map((name) => [
    name,
    sha256(readFileSync(here(`./${name}`))),
  ])
  const figtree = [500, 600, 700].map((weight) => [weight, sha256(readFileSync(join(figtreeDir(), `figtree-latin-${weight}-normal.woff`)))])
  const pkg = Schema.decodeUnknownSync(PackageSchema)(JSON.parse(readFileSync(here("../../package.json"), "utf8")))
  const manifest = {
    texts: locales.map((locale) => [locale, cardTexts(copyFor(locale))]),
    logo: sha256(readFileSync(paths.logo)),
    fontsLock: sha256(readFileSync(join(paths.fontsDir, "fonts.lock.json"))),
    figtree,
    sources,
    versions: [pkg.devDependencies.satori, pkg.devDependencies["@resvg/resvg-wasm"]],
  }
  return sha256(new TextEncoder().encode(JSON.stringify(manifest)))
}

// ---------------------------------------------------------------- build

export interface BuildOptions {
  readonly paths: Paths
  /** The page copy per locale. Tests substitute their own. */
  readonly copyFor?: (locale: Locale) => PageCopy
  readonly limits?: Limits
}

export interface Built {
  /** Output files by path relative to the public directory. */
  readonly images: ReadonlyMap<string, Uint8Array>
  readonly assets: ShareAssets
  readonly moduleSource: string
}

async function shareImage(fonts: FontSet, label: string, element: ReactElement, width: number, height: number, limit: number): Promise<Uint8Array> {
  const raster = await rasterizeRgba(await drawSvg(element, width, height, fonts))
  let png: Uint8Array
  try {
    png = encodeIndexedPng(quantize(raster, { maxColors: MAX_COLORS, pinned: BRAND_COLORS }))
  } catch (error) {
    throw new Error(`${label}: ${error instanceof Error ? error.message : String(error)}`, { cause: error })
  }
  if (png.length > limit) throw new Error(`${label} is ${png.length} bytes, ${png.length - limit} over its ${limit}-byte limit`)
  return png
}

function imageInfo(path: string, bytes: Uint8Array, width: number, height: number): ShareAssets["ogZh"] {
  return { path: `/${path}`, version: sha256(bytes).slice(0, 8), width, height }
}

export async function build({ paths, copyFor = pageCopy, limits = DEFAULT_LIMITS }: BuildOptions): Promise<Built> {
  const fonts = loadFonts(paths.fontsDir)
  const copies = locales.map((locale) => [locale, copyFor(locale)] as const)
  const missing = [...new Set(copies.flatMap(([, copy]) => missingGlyphs(cardTexts(copy).join(""), fonts)))]
  if (missing.length > 0) {
    throw new Error(`the share copy needs glyphs that no font covers: ${missing.join(" ")}. Run \`bun run og:fonts\` to fetch the slices that cover them.`)
  }

  const logoSvg = readFileSync(paths.logo, "utf8")
  const logo = svgDataUri(logoSvg)
  const input = (locale: Locale): Parameters<typeof ogCard>[0] => ({ copy: copyFor(locale), stack: fonts.stack, logo })

  const ogZh = await shareImage(fonts, "og-zh.png", ogCard(input("zh")), 1200, 630, limits.wide)
  const ogEn = await shareImage(fonts, "og-en.png", ogCard(input("en")), 1200, 630, limits.wide)
  const square = await shareImage(fonts, "square.png", squareCard({ logo }), 600, 600, limits.square)
  const favicon32 = await rasterizePng(logoSvg, 32)
  const appleTouchIcon = await rasterizePng(
    `<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180" viewBox="0 0 180 180"><rect width="180" height="180" fill="${INK}"/><image href="${logo}" width="180" height="180"/></svg>`,
  )

  const assets: ShareAssets = {
    inputsHash: computeInputsHash(paths, copyFor),
    ogZh: imageInfo(OUTPUT.ogZh, ogZh, 1200, 630),
    ogEn: imageInfo(OUTPUT.ogEn, ogEn, 1200, 630),
    square: imageInfo(OUTPUT.square, square, 600, 600),
    favicon32: imageInfo(OUTPUT.favicon32, favicon32, 32, 32),
    appleTouchIcon: imageInfo(OUTPUT.appleTouchIcon, appleTouchIcon, 180, 180),
  }
  const images = new Map<string, Uint8Array>([
    [OUTPUT.ogZh, ogZh],
    [OUTPUT.ogEn, ogEn],
    [OUTPUT.square, square],
    [OUTPUT.favicon32, favicon32],
    [OUTPUT.appleTouchIcon, appleTouchIcon],
  ])
  return { images, assets, moduleSource: moduleSource(assets) }
}

export function write(paths: Paths, built: Built): void {
  for (const [name, bytes] of built.images) {
    const target = join(paths.publicDir, name)
    mkdirSync(dirname(target), { recursive: true })
    writeFileSync(target, bytes)
  }
  mkdirSync(dirname(paths.assetsModule), { recursive: true })
  writeFileSync(paths.assetsModule, built.moduleSource)
}

export async function generate(options: BuildOptions): Promise<Built> {
  const built = await build(options)
  write(options.paths, built)
  return built
}

// ---------------------------------------------------------------- checking committed output

const SLOTS = [
  { key: "ogZh", file: OUTPUT.ogZh },
  { key: "ogEn", file: OUTPUT.ogEn },
  { key: "square", file: OUTPUT.square },
  { key: "favicon32", file: OUTPUT.favicon32 },
  { key: "appleTouchIcon", file: OUTPUT.appleTouchIcon },
] as const

/**
 * Is what is committed still what the inputs would produce? Compares the inputs' hash with the recorded one and
 * each PNG's content hash with its recorded version. It does not render, so it does not depend on the platform
 * that rasterizes. Returns the problems found; an empty list means up to date.
 */
export function check({ paths, copyFor = pageCopy }: Pick<BuildOptions, "paths" | "copyFor">): string[] {
  try {
    verifyFontFiles(paths.fontsDir, readFontLock(paths.fontsDir))
  } catch (error) {
    return [messageOf(error)]
  }
  let recorded: ShareAssets
  try {
    recorded = parseModule(readFileSync(paths.assetsModule, "utf8"))
  } catch (error) {
    return [`share-assets.gen.ts is missing or unreadable: ${messageOf(error)}`]
  }
  const problems: string[] = []
  if (computeInputsHash(paths, copyFor) !== recorded.inputsHash) {
    problems.push(
      "the inputs changed since the images were generated: the share copy, logo.svg, a template, a font or a dependency version no longer matches share-assets.gen.ts",
    )
  }
  for (const { key, file } of SLOTS) {
    const info = recorded[key]
    if (info.path !== `/${file}`) problems.push(`share-assets.gen.ts records ${info.path} for ${file}`)
    let bytes: Uint8Array
    try {
      bytes = readFileSync(join(paths.publicDir, file))
    } catch {
      problems.push(`${file} is missing`)
      continue
    }
    if (sha256(bytes).slice(0, 8) !== info.version) {
      problems.push(`${file} does not match the version recorded in share-assets.gen.ts (was it replaced or edited by hand?)`)
      continue
    }
    try {
      const png = parsePng(bytes)
      if (png.width !== info.width || png.height !== info.height) {
        problems.push(`${file} is ${png.width}x${png.height}, but share-assets.gen.ts records ${info.width}x${info.height}`)
      }
    } catch (error) {
      problems.push(`${file} is not a valid PNG: ${messageOf(error)}`)
    }
  }
  return problems
}

/** Renders everything again and compares it, byte for byte, with what is committed. Writes nothing. */
export async function verifyRender(options: BuildOptions): Promise<string[]> {
  const built = await build(options)
  const mismatches: string[] = []
  for (const [name, bytes] of built.images) {
    let committed: Uint8Array
    try {
      committed = readFileSync(join(options.paths.publicDir, name))
    } catch {
      mismatches.push(`${name} is missing`)
      continue
    }
    if (sha256(committed) !== sha256(bytes)) mismatches.push(`${name} differs from a fresh render`)
  }
  let committedModule = ""
  try {
    committedModule = readFileSync(options.paths.assetsModule, "utf8")
  } catch {
    // reported below: an unreadable module cannot equal the fresh one
  }
  if (committedModule !== built.moduleSource) mismatches.push("share-assets.gen.ts differs from a fresh render")
  return mismatches
}
