/**
 * Generated artifacts in this repo:
 * - apps/web/src/routeTree.gen.ts, regenerated by the TanStack plugin during the Vite build.
 * - The share images and icon PNGs (apps/web/public/share/*.png, favicon-32.png, apple-touch-icon.png) and
 *   apps/web/src/share-assets.gen.ts, written by apps/web/scripts/og from the page copy, logo.svg and the fonts.
 *
 * `generate` rebuilds both. `generate:check` fails when either is stale: the share assets by comparing a hash
 * of their inputs (no rendering), the route tree by building and diffing the committed file.
 * Never edit a generated file by hand.
 */
import { $ } from "bun"

const target = "apps/web/src/routeTree.gen.ts"
const checking = process.argv.includes("--check")

// Output stays visible: when the share assets are stale, og says what changed and what to run.
const og = checking ? await $`bun run --cwd apps/web og --check`.nothrow() : await $`bun run --cwd apps/web og`.nothrow()
if (og.exitCode !== 0) process.exit(og.exitCode)

await $`bun run build`.quiet()

if (checking) {
  const diff = await $`git diff --exit-code -- ${target}`.quiet().nothrow()
  if (diff.exitCode !== 0) {
    console.error(`${target} is stale. Run \`bun run generate\` and commit the result.`)
    process.exit(1)
  }
  console.log(`${target} is up to date.`)
} else {
  console.log(`${target} regenerated.`)
}
